CREATE TABLE IF NOT EXISTS PlayerEntity (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
`name` TEXT NOT NULL, 
`points` INTEGER NOT NULL, 
`team` INTEGER NOT NULL)

CREATE TABLE IF NOT EXISTS TikBumEntity (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
`word` TEXT NOT NULL)

INSERT INTO TikBumEntity (word)
    SELECT * FROM (VALUES('lol'))
    WHERE NOT EXISTS (
    SELECT id FROM TikBumEntity
    WHERE id = 13)
